#!/usr/bin/env bash
#takes 4 args and uses it to transfer a file to a server

if [ $# -lt 3 ]
then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
