#!/usr/bin/env bash
# sets the webserver to permanently redirect
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
Service="\\\tlocation /redirect_me{\n\treturn 301 https://www.google.com/search?q=berserk%20manga&tbm=isch&rlz;\n\t}"
sudo sed -i "26i $Service" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
