#!/usr/bin/bash env

#creates a unique 404 error page
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
Server="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}"
sudo sed -i "29i $Server" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
